# Generated by Django 4.1.5 on 2023-02-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="quote",
            field=models.CharField(default="USD", max_length=10),
        ),
    ]
