# Generated by Django 4.1.5 on 2023-02-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0002_alter_currency_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="last_24h",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
